[package]
name = "rust_kernels"
version = "0.1.0"
edition = "2021"

[dependencies]
nvvm = { path = "../nvvm-0.2" }
nvjitlink = { path = "../nvjitlink" }
cuda = { path = "../cuda" }

[build]
rustc = "../../rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc"